//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBCarRent
{
    using System;
    using System.Collections.Generic;
    
    public partial class Car
    {
        public int Id { get; set; }
        public string Photo { get; set; }
        public string Model { get; set; }
        public Nullable<int> PricePerDay { get; set; }
        public Nullable<int> CostOfDayOverdue { get; set; }
        public string Availability { get; set; }
        public Nullable<int> Year { get; set; }
        public string GearBox { get; set; }
        public Nullable<int> Mileage { get; set; }
        public string CarNumber { get; set; }
        public string Branch { get; set; }
    }
}
